# ============================================
# Hospital Management System Infrastructure
# Modular Docker Compose Configuration
# ============================================
#
# This file orchestrates all service infrastructure
# by including individual service compose files.
#
# Usage:
#   docker-compose up -d              # Start all services
#   docker-compose down               # Stop all services
#   docker-compose down -v            # Stop and remove volumes
#   docker-compose ps                 # List running services
#   docker-compose logs -f [service]  # View logs
#
# Structure:
#   - infrastructure/docker-compose.yml (RabbitMQ, Redis, pgAdmin)
#   - apps/patient-service/docker-compose.yml (Patient DB)
#   - apps/auth-service/docker-compose.yml (Auth DB)
# ============================================

include:
  # Shared Infrastructure Services
  - path: infrastructure/docker-compose.yml
    env_file: .env

  # Patient Service Database
  - path: apps/patient-service/docker-compose.yml
    env_file: .env

  # Auth Service Database
  - path: apps/auth-service/docker-compose.yml
    env_file: .env

# ============================================
# Network Configuration
# ============================================
# The hospital-network must be created before starting services
# Run: docker network create hospital-network
# ============================================
networks:
  hospital-network:
    name: ${NETWORK_NAME:-hospital-network}
    driver: bridge
    external: true
