# ============================================
# Auth Service Infrastructure
# ============================================

services:
  # PostgreSQL - Auth Service Database
  postgres-auth:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    container_name: postgres-auth
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${AUTH_DB_NAME:-auth_db}
      POSTGRES_USER: ${POSTGRES_USER:-hospital}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hospital123}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8'
      PGDATA: /var/lib/postgresql/data/pgdata

    env_file:
      - ../../.env

    ports:
      - '${AUTH_DB_PORT:-5434}:5432'

    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-hospital} -d ${AUTH_DB_NAME:-auth_db}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m

    networks:
      - hospital-network

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

# ============================================
# Named Volumes
# ============================================
volumes:
  postgres-auth-data:
    name: hospital-postgres-auth-data
    driver: local

# ============================================
# Networks
# ============================================
networks:
  hospital-network:
    name: ${NETWORK_NAME:-hospital-network}
    driver: bridge
    external: true
