# ============================================
# Shared Infrastructure Services
# ============================================

services:
  # ==========================================
  # Redis - Caching and Session Management
  # ==========================================
  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    container_name: redis
    restart: unless-stopped

    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

    env_file:
      - ../.env

    ports:
      - '${REDIS_PORT:-6379}:6379'

    volumes:
      - redis-data:/data

    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m

    networks:
      - hospital-network

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  # ==========================================
  # RabbitMQ - Message Broker
  # ==========================================
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-3.13-management-alpine}
    container_name: rabbitmq
    restart: unless-stopped

    hostname: rabbitmq-hospital

    env_file:
      - ../.env

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /

    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m

    networks:
      - hospital-network

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  # ==========================================
  # pgAdmin - PostgreSQL Management UI
  # ==========================================
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    container_name: pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'

    env_file:
      - ../.env

    ports:
      - '${PGADMIN_PORT:-5050}:80'

    volumes:
      - pgadmin-data:/var/lib/pgadmin

    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m

    networks:
      - hospital-network

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

# ============================================
# Named Volumes
# ============================================
volumes:
  redis-data:
    name: hospital-redis-data
    driver: local

  rabbitmq-data:
    name: hospital-rabbitmq-data
    driver: local

  pgadmin-data:
    name: hospital-pgadmin-data
    driver: local

# ============================================
# Networks
# ============================================
networks:
  hospital-network:
    name: ${NETWORK_NAME:-hospital-network}
    driver: bridge
    external: true
