name: Nx Monorepo CI Pipeline

on:
  # RUN WHEN
  # + PULL: MAIN
  # + PUSH: MAIN
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Tính toán các dự án bị ảnh hưởng và Chạy Lint/Test
  affected-check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # GET NODEJS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint on Affected Projects
        run: npx nx affected:lint --base=origin/main --head=${{ github.event.pull_request.head.sha || github.sha }}

      - name: Run Tests (Unit & E2E) on Affected Projects
        run: npx nx affected:test --base=origin/main --head=${{ github.event.pull_request.head.sha || github.sha }} --coverage
